name: Jekyll site CI

on:
  schedule:
    - cron:  '0 0 */7 * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true 
      - run: |
          ruby -v
          bundle exec ruby _scripts/get-top-list.rb
          bundle exec ruby _scripts/update.rb
          git config user.name AppStore bot
          git config user.email github-actions@github.com
          git add _apps _data
          git commit -m "Commit generated files"
          git push
      - name: Build the site in the jekyll/builder container
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
